# DualCalc Configuration File
# 雙視窗計算機 全局設定檔

# App Configuration (計算機相關設定)
calc:
  # The default width of a single calculator window. 
  # If Dual Mode is off, window is this wide. If on, window is (this * 2).
  # 單一區塊的預設寬度。雙開時將會變成預設寬度 * 2。
  # default:380
  defaultAppWidth: 380

  # The default height of the window.
  # 視窗的預設高度。
  # default:700
  defaultAppHeight: 700

  # Default state of Dual Mode on startup.
  # 啟動時是否預設開啟雙視窗模式。
  # default:true
  isDualModeOnStartup: true

  # Default font size for calculator buttons.
  # 計算機按鈕的預設字體大小。
  # default:18
  defaultButtonFontSize: 24

  # Default font size for calculator function buttons (e.g. 1/x, x², %, CE, C, ⌫).
  # 計算機功能按鈕的預設字體大小 (例如 1/x, x², %, CE, C, ⌫)。
  # default:14
  defaultFuncButtonFontSize: 24

  # Default font size for calculator memory buttons (e.g. MC, MR, M+, M-, MS).
  # 計算機記憶體按鈕的預設字體大小 (例如 MC, MR, M+, M-, MS)。
  # default:12
  defaultMemButtonFontSize: 14

# Setting Configuration (全域設定)
setting:
  # Default Language: 'zh-Hant' or 'zh-Hans'
  # 預設語系，支援 'zh-Hant' (繁體), 'zh-Hans' (簡體)
  language: zh-Hant

  # Default Theme: 'Light', 'Dark', or 'System'
  # 預設主題，支援 'Light', 'Dark', 'System'
  theme: System
